#!/bin/bash 
#PBS -l nodes=1:ppn=20
#PBS -l walltime=1:00:00:00
#PBS -N preprocess_1
#PBS -o preprocess.o
#PBS -e preprocess.e
#PBS -q workq
#PBS -A hpc_mlde_gb1

# Define variables
# needs to updated to glycan-protein
ipath=GB1_sequences
        # Path to folder that contains all results from AlphaFold (Default: input)
opath=prepackedGlycanInput
        # Path to folder that put all output files  (Default: output)
ppn=20
        # Number of processes per node  (Default: 20)
        
# Activate pymol environment
module load python/3.8.5-anaconda
source activate pymol

# Load GNU Parallel
module load gnuparallel/20190222/intel-19.0.5

# Change work directory
cd $PBS_O_WORKDIR

# Create a list of input files
ifiles=(`cd $ipath; find . -name 'ranked_0.pdb' | sed -e 's|^./||g' -e  's|/ranked_0.pdb||g'`)

# Process AlphaFold results
# !!NEED TO UPDATE script_glycan.pml !!
parallel --workdir $PBS_O_WORKDIR -j$ppn \
         "sed -e 's|INPUT|$ipath/{}/ranked_0.pdb|g' -e 's|OUTPUT|$opath/{}.pdb|g' script_glycan.pml | pymol -cpq" ::: ${ifiles[@]}
         
# Deactivate pymol environment
conda deactivate

