#!/bin/bash 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=1:00:00:00
#PBS -N generateEncode
#PBS -o generateEncode
#PBS -e generateEncodeERROR
#PBS -q single
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu

date
cd $PBS_O_WORKDIR

conda activate mlde

python /ddnA/project/jjung1/packages/MLDE/generate_encoding.py transformer GB1_Peter --fasta /home/pvalle6/MLDE/GB1_Alignment_Clean.a2m  --positions V37 D38 G39 V52 --ouput /home/pvalle6/MLDE/ --batch_size 32 



#(END_OF_FILE)