#!/bin/bash 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=1:00:00:00
#PBS -N generateEncode
#PBS -o generateEncode
#PBS -e generateEncodeERROR
#PBS -q single
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu

date
#conda activate mlde
module load python/3.8.5-anaconda
source activate mlde
python /ddnA/project/jjung1/packages/MLDE/generate_encoding.py transformer GB1_Peter --fasta /work/pvalle6/GB1_Alignment_Clean.a2m  --positions V37 D38 G39 V52 --output /work/pvalle6/ --batch_size 32 



#(END_OF_FILE)