#!/bin/bash 
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N installMLDE_1
#PBS -o installMLDE.o
#PBS -e installMLDE.e
#PBS -q workq
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu


#imma just install of mlde on my work, idc
	
date
#grabs state at start of script

module load python/3.8.5-anaconda
		#activate enviroment MLDE2 for predictZero
cd $PBS_O_WORKDIR
git clone --recurse-submodules https://github.com/fhalab/MLDE.git
cd ./MLDE
conda env create -f mlde.yml
conda env create -f mlde2.yml
conda env create -f deep_sequence.yml

# might need to PIP some modules in??? add in after error is displayed

#(END_OF_FILE)