#!/bin/bash 
#PBS -l nodes=1:ppn=20
#PBS -l walltime=6:00:00
#PBS -N prepack
#PBS -o prepack.o
#PBS -e prepack.e 
#PBS -q workq
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu

# Variables
# update GlycanDock Scripts and glycandock location and its relevant references
export flexpepdock=/project/jjung1/packages/rosetta/main/source/bin/FlexPepDocking.default.linuxgccrelease
        # Path to FlexPepDocking
export ipath=Protein_peptide_complex
        # Path to folder that contains all input .pdb files  (Default: input)
export opath=Prepacked_protein_peptide_complex
        # Path to folder that put all output files  (Default: output)

# Load GNU Parallel
module load gnuparallel/20190222/intel-19.0.5

# Change work directory
cd $PBS_O_WORKDIR

# Create output folders based on input file list
export ifiles=`ls $ipath`
#for ifile in $ifiles
#do
#    mkdir $opath/$ifile
#done

# Run
# update to glycandock
parallel $flexpepdock @prepack_flags_glycan -in:path $ipath/ -out:prefix $opath/ -scorefile $opath/{/.}.score.sc -s {} ::: $ifiles
#parallel $flexpepdock @prepack_flags -in:path $ipath/ -out:prefix $opath/{/}/ -scorefile $opath/{/}/{/.}.score.sc -s {} ::: $ifiles

