#!/bin/bash 
#PBS -l nodes=1:ppn=20
#PBS -l walltime=0:30:00
#PBS -N zeroShot_1
#PBS -o zeroShot.o
#PBS -e zeroShot_EPDE.e 
#PBS -q workq
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu



	# Variables
export opath=/ddnA/project/jjung1/pvalle6/output/
        # Path to folder that put all output files 
export WORK_DIR=/work/pvalle6/
		#sets enviroment variables for the process	
date
	#grabs state at start of script
module load python/3.8.5-anaconda
	#load conda env
conda activate
	#changes node to work 
cd $WORK_DIR
	#changes it to the MLDE directory 
cd ./MLDE
	# activates neccesarry enviroment
conda activate mlde2
	# run zeroShot on workdirectory 
python predict_zero_shot.py --positions V39 D40 G41 V54 \
	--models esm1b_t33_650M_UR50S \ 
	EVmutation esm_msa1_t12_100M_UR50S \
	--fasta ./code/validation/basic_test_data/2GI9.fasta --alignment \
	./code/validation/basic_test_data/GB1_Alignment.a2m --evmutation_model \
	./code/validation/basic_test_data/GB1_EVcouplingsModel.model --include_conditional \
	--batch_size 32 --output ../outputfiles_mlde/



#(END_OF_FILE)