#!/bin/bash 
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:30:00
#PBS -N zeroShot_EPDE
#PBS -o /ddnA/project/jjung1/pvalle6/output/zeroShotPredictionLane
#PBS -e zeroShot_EPDE.e 
#PBS -q single
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu

# Variables
export predictZeroShot=/ddnA/project/jjung1/packages/MLDE/predict_zero_shot.py
        # Path to predictZeroShot
export opath=/ddnA/project/jjung1/pvalle6/output/
        # Path to folder that put all output files  (Default: output)

		#sets enviroment variables for the process
export HOME_DIR=/ddnA/project/jjung1/packages/MLDE/
export WORK_DIR=/work/pvalle6/zeroShot
		
date
		#grabs state at start of script

		# Load GNU Parallel
module load python/3.8.5-anaconda
		#activate enviroment MLDE2 for predictZero
source activate mlde2

		#makes sure the directory exists	
mkdir -p $WORK_DIR
		#Change work directory

cd $WORK_DIR
python /ddnA/project/jjung1/packages/MLDE/predict_zero_shot.py --positions V39 D40 G41 V54 --models EVmutation --alignment /ddnA/project/jjung1/pvalle6/GB1_Alignment.a2m --evmutation_model /ddnA/project/jjung1/pvalle6/GB1_EVcouplingsModel.model --output /ddnA/project/jjung1/pvalle6/output

#(END_OF_FILE)